version: "3.8"
services:
  api:
    container_name: "api"
    build:
      dockerfile: Dockerfile
      context: .
    ports: 
      - "8080:80"
    depends_on:
      - "postgres"
    env_file:
      - ./.env.docker
  
  postgres:
    container_name: "postgres"
    image: "postgres:14"
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloud-runner
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    
volumes:
  db-data:
  